# Generated by Django 5.1.6 on 2025-02-28 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Financial',
            fields=[
                ('account', models.IntegerField()),
                ('invoice', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Register_pharmacy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_medicine', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
